models_data = [
    {
        "name": "Gigi Hadid",
        "email": "gigihadid@gmail.com",
        "image": "img/model1.webp",
        "description": "American fashion model, known for her work with Tommy Hilfiger and Victoria's Secret.",
        "instagram": "gigihadid",
        "height": "5'10",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "walked for Tommy Hilfiger",
        "notable_work": "Victoria's Secret",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Kendall Jenner",
        "email": "kendalljenner@gmail.com",
        "image": "img/model2.webp",
        "description": "American model and media personality. Part of the Kardashian-Jenner family.",
        "instagram": "kendalljenner",
        "height": "5'10",
        "agency": "The Society Management",
        "specialization": "Model",
        "location": "Los Angeles",
        "experience": "Various",
        "highlights": "walked for various brands",
        "notable_work": "Kardashian",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Kylie Jenner",
        "email": "kyliejenner@gmail.com",
        "image": "img/model3.png",
        "description": "American model and media personality. Part of the Kardashian-Jenner family.",
        "instagram": "kyliejenner",
        "height": "5'10",
        "agency": "The Society Management",
        "specialization": "Model",
        "location": "Los Angeles",
        "experience": "Various",
        "highlights": "walked for various brands",
        "notable_work": "Kardashian",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Khloé Kardashian",
        "email": "khloé_kardashian@gmail.com",
        "image": "img/model4.png",
        "description": "American model and media personality. Part of the Kardashian-Jenner family.",
        "instagram": "khloe_kardashian",
        "height": "5'10",
        "agency": "The Society Management",
        "specialization": "Model",
        "location": "Los Angeles",
        "experience": "Various",
        "highlights": "walked for various brands",
        "notable_work": "Kardashian",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Pamela Anderson",
        "email": "pamela_anderson@gmail.com",
        "image": "img/model5.png",
        "description": "American model and media personality. Not Part of the Kardashian-Jenner family.",
        "instagram": "pamela_anderson",
        "height": "5'10",
        "agency": "The Model Agency",
        "specialization": "Model",
        "location": "Los Angeles",
        "experience": "Various",
        "highlights": "walked for various brands",
        "notable_work": "Not the Kardashian",
        "weight": "130 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Adriana Lima",
        "email": "adriana_lima@gmail.com",
        "image": "img/model6.png",
        "description": "Brazilian model and actress, best known as a Victoria's Secret Angel.",
        "instagram": "adrianalima",
        "height": "5'10",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "Victoria's Secret Angel",
        "notable_work": "Victoria's Secret",
        "weight": "125 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Alessandra Ambrosio",
        "email": "alessandra_ambrosio@gmail.com",
        "image": "img/model7.png",
        "description": "Brazilian model, actress, and businesswoman. Known for her work with Victoria's Secret.",
        "instagram": "alessandraambrosio",
        "height": "5'10",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "Los Angeles",
        "experience": "High Fashion",
        "highlights": "Victoria's Secret Angel",
        "notable_work": "Victoria's Secret",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Bella Hadid",
        "email": "bella_hadid@gmail.com",
        "image": "img/model8.png",
        "description": "American model, sister of Gigi Hadid.",
        "instagram": "bellahadid",
        "height": "5'9",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Fashion Week",
        "weight": "118 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Cara Delevingne",
        "email": "cara_delevingne@gmail.com",
        "image": "img/model9.png",
        "description": "English model, actress, and singer.",
        "instagram": "caradelevingne",
        "height": "5'8",
        "agency": "CAA Fashion",
        "specialization": "Fashion Model",
        "location": "London",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "115 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Candice Swanepoel",
        "email": "candice_swanepoel@gmail.com",
        "image": "img/model10.png",
        "description": "South African model, best known as a Victoria's Secret Angel.",
        "instagram": "angelcandices",
        "height": "5'10",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "Victoria's Secret Angel",
        "notable_work": "Victoria's Secret",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Doutzen Kroes",
        "email": "doutzen_kroes@gmail.com",
        "image": "img/model11.png",
        "description": "Dutch model and actress.",
        "instagram": "doutzen",
        "height": "5'10",
        "agency": "DNA Model Management",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Emily Ratajkowski",
        "email": "emrata@gmail.com",
        "image": "img/model12.png",
        "description": "American model and actress.",
        "instagram": "emrata",
        "height": "5'7",
        "agency": "Ford Models",
        "specialization": "Fashion Model",
        "location": "Los Angeles",
        "experience": "Various",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "115 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Gisele Bündchen",
        "email": "gisele@gmail.com",
        "image": "img/model13.png",
        "description": "Brazilian model, actress, and businesswoman.",
        "instagram": "gisele",
        "height": "5'11",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "Boston",
        "experience": "High Fashion",
        "highlights": "Victoria's Secret Angel",
        "notable_work": "Victoria's Secret",
        "weight": "125 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Hailey Bieber",
        "email": "haileybieber@gmail.com",
        "image": "img/model14.png",
        "description": "American model and media personality.",
        "instagram": "haileybieber",
        "height": "5'7",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "Various",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "115 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Irina Shayk",
        "email": "irinashayk@gmail.com",
        "image": "img/model15.png",
        "description": "Russian model and actress.",
        "instagram": "irinashayk",
        "height": "5'10",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Green",
        "media_links": "www.example.com"
    },
    {
        "name": "Joan Smalls",
        "email": "joansmalls@gmail.com",
        "image": "img/model16.png",
        "description": "Puerto Rican model.",
        "instagram": "joansmalls",
        "height": "5'10",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Karlie Kloss",
        "email": "karliekloss@gmail.com",
        "image": "img/model3.png",
        "description": "American model and businesswoman.",
        "instagram": "karliekloss",
        "height": "6'2",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "Victoria's Secret Angel",
        "notable_work": "Victoria's Secret",
        "weight": "130 lbs",
        "measurements": "34-24-34",
        "hair_color": "Blonde",
        "eye_color": "Blue",
        "media_links": "www.example.com"
    },
    {
        "name": "Lily Aldridge",
        "email": "lilyaldridge@gmail.com",
        "image": "img/model4.png",
        "description": "American model.",
        "instagram": "lilyaldridge",
        "height": "5'9",
        "agency": "IMG Models",
        "specialization": "Fashion Model",
        "location": "Los Angeles",
        "experience": "High Fashion",
        "highlights": "Victoria's Secret Angel",
        "notable_work": "Victoria's Secret",
        "weight": "115 lbs",
        "measurements": "34-24-34",
        "hair_color": "Brown",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Liu Wen",
        "email": "liuwen@gmail.com",
        "image": "img/model5.png",
        "description": "Chinese model.",
        "instagram": "liuwenlw",
        "height": "5'10",
        "agency": "The Society Management",
        "specialization": "Fashion Model",
        "location": "New York",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Black",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    },
    {
        "name": "Naomi Campbell",
        "email": "naomicampbell@gmail.com",
        "image": "img/model6.png",
        "description": "British model, actress, and businesswoman.",
        "instagram": "naomi",
        "height": "5'9",
        "agency": "DNA Model Management",
        "specialization": "Fashion Model",
        "location": "London",
        "experience": "High Fashion",
        "highlights": "walked for various brands",
        "notable_work": "Runways",
        "weight": "120 lbs",
        "measurements": "34-24-34",
        "hair_color": "Black",
        "eye_color": "Brown",
        "media_links": "www.example.com"
    }
]

    # ... (rest of your data)
names = [model["name"] for model in models_data]

print(names)